fix: Remove all variables and most functions from global scope (#61)
To avoid name collisions on sites due to common names, e.g. Uncaught
SyntaxError: Identifier 'options' has already been declared

This also updates to use version 1.0.2 of trace-anything.

Changes have been formatted with Chromium's JavaScript formatter.

Fixes #44